# Copyright 2025 Accenture.
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "mw_log"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true, features = ["std"] }

[build-dependencies]
cc = { workspace = true }
