@startuml configuration_static
title Configuration Static

package "bmw::json" {
  class JsonParser {
    +FromFile(path) : Result<bmw::json::Any>
  }
}

package "bmw::os" as os {
  class Unistd {
    ---
    +access()
  }
  class Stdlib {
    ---
    +getenv()
  }
  
  class "utils/path" as Path {
    ---
    +get_exec_path() : Result
    +get_parent_dir() : string
  }
}

interface Recorder {
}

class TextRecorder {}

class DataRouterRecorder {
  -configuration : bwm::mw::log::Configuration
}
class FileRecorder {}
class EmptyRecorder {}
class CompositeRecorder {
  -config_ : bwm::mw::log::Configuration
}

class RecorderComposite{
  recorders_: std::vector<Recorder>
  ---
  RecorderComposite(recorders: std::vector<Recorder>)
}

class Configuration {
  -ecu_id_ : LoggingIdentifier
  -app_id_ : LoggingIdentifier
  -app_description_ : string
  -log_mode_ : unordered_set
  -log_file_path_ : string
  -default_log_level_ : LogLevel
  -default_console_log_level_ : LogLevel
  -context_log_level_ : ContextLogLevelMap
  -stack_buffer_size_ : size_t
  -ring_buffer_size_ : size_t
  -ring_buffer_overwrite_on_full_ : bool
  -number_of_slots_ : size_t
  -slot_size_bytes_ : size_t
  -data_router_uid_ : size_t
  -dynamic_datarouter_identifiers_ : bool
  --
  +Configuration()
  +GetEcuId() : string_view
  +SetEcuId(value) : void
  +GetAppId() : string_view
  +SetAppId(value) : void
  +GetAppDescription() : string_view
  +SetAppDescription(value) : void
  +GetLogMode() : unordered_set
  +SetLogMode(value) : void
  +GetLogFilePath() : string_view
  +SetLogFilePath(value) : void
  +GetDefaultLogLevel() : LogLevel
  +SetDefaultLogLevel(value) : void
  +GetDefaultConsoleLogLevel() : LogLevel
  +SetDefaultConsoleLogLevel(value) : void
  +GetContextLogLevel() : ContextLogLevelMap
  +SetContextLogLevel(value) : void
  +GetStackBufferSize() : size_t
  +SetStackBufferSize(value) : void
  +GetRingBufferSize() : size_t
  +SetRingBufferSize(value) : void
  +GetRingBufferOverwriteOnFull() : bool
  +SetRingBufferOverwriteOnFull(value) : void
  +GetNumberOfSlots() : size_t
  +SetNumberOfSlots(value) : void
  +GetSlotSizeInBytes() : size_t
  +SetSlotSizeInBytes(value) : void
  +SetDataRouterUid(value) : void
  +GetDataRouterUid() : size_t
  +GetDynamicDatarouterIdentifiers() : bool
  +SetDynamicDatarouterIdentifiers(value) : void
  +IsLogLevelEnabled(log_level, context, check_for_console) : bool
}

interface ITargetConfigReader {
  ---
  +ReadConfig() : bmw::Result<Configuration>
}

class TargetConfigReader {
  -discoverer_ : std::unique_ptr<IConfigurationFileDiscovery>
  ---
  +TargetConfigReader(discoverer)
  +ReadConfig() : Result
}

class TargetConfigReaderMock {}

interface IConfigurationFileDiscoverer {
  ---
  +FindConfigurationFiles() : vector<std::string>
}

class ConfigurationFileDiscoverer {
  -path_ : unique_ptr<os::Path>
  -stdlib_ : unique_ptr<os::Stdlib>
  -unistd_ : unique_ptr<os::Unistd>
  ---
  +ConfigurationFileDiscoverer(path: std::unique_ptr<os::Path>,
                               stdlib: std::unique_ptr<os::Stdlib>,
                               unistd: std::unique_ptr<os::Unistd>)
  +FindConfigurationFiles() : vector<std::string>
}

class ConfigurationFileDiscovererMock {}

class RecorderFactory {
  ---
  -GetRemoteRecorder(config) : std::unique_ptr<Recorder>
  -GetFileRecorder(config, fcntl) : std::unique_ptr<bmw::os::Fcntl>&>
  -GetConsoleRecorder(config) : std::unique_ptr<Recorder>
  +CreateFromConfiguration() : std::unique_ptr<Recorder>
  +CreateFromConfiguration(const std::unique_ptr<const ITargetConfigReader>) : std::unique_ptr<Recorder>
  +CreateWithConsoleLoggingOnly() : std::unique_ptr<Recorder>
  +CreateStub() : std::unique_ptr<Recorder>
  +CreateRecorderFromLogMode(const LogMode&, const Configuration&, const std::unique_ptr<bmw::os::Fcntl>) : std::unique_ptr<Recorder>
}

interface IRecorderFactory {
  ---
  +CreateFromConfiguration() : unique_ptr<Recorder>
  +CreateWithConsoleLoggingOnly() : std::unique_ptr<Recorder>
  +CreateStub() : std::unique_ptr<Recorder>
}

class Runtime {}

class LoggingIdentifier {
  +kMaxLength : std::size_t
  +data_ : std::array<std::string_view::value_type, kMaxLength>
  ---
  +LoggingIdentifier(const std::string_view)
  +GetStringView(const std::string_view)
  +operator_equal(const LoggingIdentifier&, const LoggingIdentifier&) : bool
  +operator_not_equal(const LoggingIdentifier&, const LoggingIdentifier&) : bool
}

' Inheritance relationships
Recorder <|-- TextRecorder
Recorder <|-- DataRouterRecorder
Recorder <|-- FileRecorder
Recorder <|-- EmptyRecorder
Recorder <|-- CompositeRecorder
Recorder <|.. RecorderComposite

ITargetConfigReader <|.. TargetConfigReader
ITargetConfigReader <|.. TargetConfigReaderMock

IConfigurationFileDiscoverer <|-- ConfigurationFileDiscoverer
IConfigurationFileDiscoverer <|-- ConfigurationFileDiscovererMock

IRecorderFactory <|-- RecorderFactory

' Composition and aggregation relationships
DataRouterRecorder *-- Configuration : owns
CompositeRecorder *-- Configuration : owns
TextRecorder *-- Configuration : owns
FileRecorder *-- Configuration : owns
Recorder --* Runtime: Owns an instance of

TargetConfigReader *-- IConfigurationFileDiscoverer
ConfigurationFileDiscoverer --> os : uses
Configuration *-- LoggingIdentifier : owns

' Usage relationships
RecorderFactory --> TargetConfigReader: uses
TargetConfigReader ..> Configuration : creates
RecorderFactory --> RecorderComposite: creates
TargetConfigReader ..> JsonParser : uses
Runtime --> RecorderFactory : Uses on initalization

note top of RecorderComposite
  Forwards the logs to all recorders
  in the list passed in the constructor.
end note

note right of RecorderFactory
  CreateForTarget(): Loads the configuration 
  and instantiates the requested recorder types.
  
  CreateForUnitTests(): Prepares a recorder
  that puts logs in standard output stream
  for unit testing.
  
  CreateStub(): Returns Empty recorder that 
  discards all the logs.
end note

note right of TargetConfigReader
  Reads config from
  /opt/<app>/etc/logging.json
  and /ecu/logging.json and creates the
  Configuration object.
end note

note bottom of TargetConfigReaderMock
  Used for unit testing the RecorderFactory.
end note

note top of DataRouterRecorder
  Configuration passed to the constructor by value.
end note

note right of ConfigurationFileDiscoverer
  Finds the file paths to the global, environmental and 
  application configuration files and returns all that exists.
  
  Global configuration:
  1. /etc/ecu_logging_config.json if it exists.
  
  Environmental configuration:
  1. path under the MW_LOG_CONFIG_FILE environmental
  variable if it defined
  
  Application configuration:
  1. <cwd>/etc/logging.json
  2. <cwd>/logging.json
  3. <binary path>/../etc/logging.json
end note

note bottom of IConfigurationFileDiscoverer
  Dependency injection for unit testing.
end note

@enduml