@startuml
start
:Block termination Signal;
:Create sender;
:Start receiver;
stop
if (Is exit requsted?) then (yes)
if (Receiver started?) then (yes)
:Send connect message;
:Unlink shared memory file;
:Request stop for connection;
:Shutdown thread pool;
if (merge

layer=-2) then (yes)
@enduml