@startuml
title Datarouter Message Client Impl Connect to Datarouter

start
:Block termination Signal;
:Create sender;
:Start receiver;
if (Receiver started?) then (Yes)
    if (Is exit requsted?) then (No)
    :Send connect message;
    stop
    else (Yes)
    endif
else (No)
    :Unlink shared memory file;
    :Request stop for connection;
    :Shutdown thread pool;
endif
:Merge;
stop
@enduml