@startuml mw_log_shared_memory_reader

package "mw::log"
{

interface ReaderFactory {
  + Create(const std::int32_t, const pid_t): amp::optional<SharedMemoryReader>
  + Default(): std::unique_ptr<ReaderFactory>
}

class ReaderFactoryImpl {
  - mman_: amp::pmr::unique_ptr<bmw::os::Mman>
  - stat_: amp::pmr::unique_ptr<bmw::os::Stat>
  --
  + Create(const std::int32_t, const pid_t): amp::optional<SharedMemoryReader>
}

class SharedMemoryReader {
  - shared_data_: SharedData&
  - unmap_callback_: UnmapCallback
  - linear_reader_: std::optional<LinearReader>
  - acquired_data_: std::optional<ReadAcquireResult>
  - number_of_acquired_bytes_: Length
  - finished_reading_after_detach_: bool
  - buffer_expected_to_read_next_: std::uint32_t
  - is_writer_detached_: bool
  - alternating_read_only_reader_: AlternatingReadOnlyReader
  --
  - DetachWriter(): void
  - IsWriterDetached(): bool
  + SharedMemoryReader(const SharedData&, const amp::span<Byte>, const amp::span<Byte>, UnmapCallback)
  + Read(const TypeRegistrationCallback&, const NewRecordCallback&): std::optional<Length>
  + PeekNumberOfBytesAcquiredInBuffer(const std::uint32_t): std::optional<Length>
  + ReadDetached(const TypeRegistrationCallback&, const NewRecordCallback&): std::optional<Length>
  + GetNumberOfDropsWithBufferFull(): Length
  + GetNumberOfDropsWithInvalidSize(): Length
  + GetRingBufferSizeBytes(): Length
  + GetNumberOfAcquiredBytes(): Length
  + IsBlockReleasedByWriters(): bool
  + NotifyAcquisitionSetReader(const ReadAcquireResult&): std::optional<Length>
}

class SharedData <<Shared Memory>> {
}

class LinearReader {
  - data_: amp::span<Byte>
  - read_index_: Length
  --
  + LinearReader(const amp::span<Byte>&)
  + Read(): amp::optional<amp::span<Byte>>
}

class "bmw::os::Mman" as Mman {
}
  
class "bmw::os::Stat" as Stat {
}

}

package "bwm::platform::datarouter" as DataRouterPackage{
class DataRouter {
  - subscriberDatabase_: SubscriberDatabase
  - databaseCallback_: WriteSubscriberDatabaseCallback
  --
  + new_source_session(): SessionPtr
  + new_subscriber_session(): SessionPtr
}
}


' Relationships
ReaderFactory <|.. ReaderFactoryImpl
ReaderFactoryImpl ..> Mman : "<< uses >>"
ReaderFactoryImpl ..> Stat : "<< uses >>"
ReaderFactoryImpl ..>  SharedMemoryReader : "<< creates >>"
SharedMemoryReader --> SharedData: "<< uses >>"
SharedMemoryReader --> LinearReader: "<< uses >>"

DataRouter --> ReaderFactory : "<< uses >>"

@enduml