@startuml
start
if (Payload size > max payload size) then (Yes)
    :Increment number of drops;
else(No)
    :Acquire data;
    if (Is data aquired?) then (Yes)
        :Write header;
        :Access memory;
        :Write payload;
        :Release acquired data;
    else(No)
        :Increment number of drops;
    endif
endif
stop
@enduml