@startuml
start
if (Payload size > max payload size) then (yes)
:Acquire data;
:Write header;
:access memory;
:Write payload;
:Release acquired data;
stop
if (Is data aquired?) then (yes)
:Increment number of drops counter due to invalid size
style=wordwrap;
:Increment number of drops counter due to buffer full
style=wordwrap;
if (merge

layer=1) then (yes)
@enduml