@startuml
start

:Flush slot call;

group "Slot Drainer"
:circular_buffer.push(LogRecord&);
repeat
    :Get next slot;
    group "Non Blocking Writer"
        repeat
            :Get next span;
            :Write file;
            if (Would block?) then (Yes)
                stop
            endif
        repeat while(Next Span Available?) is (Yes) not (All Data Written)
    endgroup
    :Load number of buffers flushed;
    if (Is limit reached?) then (Yes)
        stop
    endif
repeat while (is buffer empty?) is (No) not (Yes)
stop
endgroup
@enduml