@startuml slot_drainer_sequence_design

participant ":Backend" as Backend
participant ":SlotDrainer" as SlotDrainer
participant ":NonBlockingWriter" as NonBlockingWriter
participant ":CircularBuffer" as CircularBuffer
participant ":MessageBuilder" as MessageBuilder
participant ":SlotAllocator<LogRecord>" as SlotAllocator

note over SlotDrainer : Slot Drainer Flush Sequence

group "First Slot"
Backend -> SlotDrainer : flush(ctx_id, log_level)
activate SlotDrainer

SlotDrainer -> CircularBuffer : push()
SlotDrainer -> CircularBuffer : pop()
SlotDrainer -> SlotAllocator : GetUnderlyingBufferFor(slot)
SlotDrainer -> MessageBuilder : SetNextMessage(log_record)

SlotDrainer -> MessageBuilder : GetNextSpan()
SlotDrainer -> NonBlockingWriter : flush()
end

group "Last Slot"

SlotDrainer -> CircularBuffer : pop()
SlotDrainer -> SlotAllocator : GetUnderlyingBufferFor(slot)
SlotDrainer -> MessageBuilder : SetNextMessage(log_record)

SlotDrainer -> MessageBuilder : GetNextSpan()
SlotDrainer -> NonBlockingWriter : flush()

SlotDrainer -> CircularBuffer : pop()
CircularBuffer -> SlotDrainer: <empty>

Backend <-- SlotDrainer
deactivate SlotDrainer

end

@enduml