@startuml verbose_logging_sequence

participant ":App" as App
participant "FreeFunctions" as FreeFunctions
participant "LogStreamFactory" as LogStreamFactory
participant ":Runtime" as Runtime
participant ":LogStream" as LogStream
participant ":DataRouterRecorder" as DataRouterRecorder
participant "DLTFormater" as DLTFormater
participant ":DataRouterBackend" as DataRouterBackend
participant "TRACE" as TRACE

App -> FreeFunctions : bmw::mw::log::Error()

FreeFunctions -> LogStreamFactory : GetStream(LogLevel)
activate LogStreamFactory

LogStreamFactory -> Runtime : GetRecorder()
Runtime -> DataRouterRecorder : create
Runtime -> LogStreamFactory : Recorder

LogStreamFactory -> LogStream : construct
activate LogStream

LogStream -> DataRouterRecorder : StartRecord(ctx, LogLevel)
activate DataRouterRecorder

DataRouterRecorder -> DataRouterBackend : ReserveSlot()

activate DataRouterBackend
DataRouterBackend -> DataRouterRecorder : amp::optional<SlotHandle>
deactivate DataRouterBackend

DataRouterRecorder -> LogStream : amp::optional<SlotHandle>

LogStream -> LogStreamFactory : LogStream
LogStreamFactory -> FreeFunctions : LogStream
deactivate LogStreamFactory
deactivate LogStream

FreeFunctions -> App : LogStream

App -> LogStream : << Some Data
activate LogStream
LogStream -> DataRouterRecorder : log(SlotHandle, Data)

DataRouterRecorder -> DataRouterBackend : GetStream(SlotHandle)
activate DataRouterBackend
DataRouterBackend -> DataRouterRecorder : std::streambuf&
deactivate DataRouterBackend

DataRouterRecorder -> DLTFormater : Log(std::streambuf&, data)
activate DLTFormater
DLTFormater -> DLTFormater: Write formatted data into stream
DLTFormater -> DataRouterRecorder
deactivate DLTFormater

DataRouterRecorder -> LogStream
deactivate DataRouterRecorder
LogStream -> App : LogStream
deactivate LogStream

App -> LogStream : Destruct
activate LogStream
LogStream -> DataRouterRecorder : StopRecord(SlotHandle)
activate DataRouterRecorder

DataRouterRecorder -> DataRouterBackend: FlushSlot(SlotHandle)
activate DataRouterBackend
DataRouterBackend -> TRACE : TRACE(LogEntry)
DataRouterBackend -> DataRouterRecorder

DataRouterRecorder -> LogStream
deactivate DataRouterBackend
deactivate DataRouterRecorder
LogStream -> App
deactivate LogStream

note over TRACE
This part will be reomved in the future,
once we can directly stream into MrWriter
This will then remove any
dynamic memory allocaitons.
end note

deactivate DataRouterBackend
deactivate LogStreamFactory
deactivate FreeFunctions

@enduml