@startuml

package "User-Facing API" {

    class "Free Functions" as FreeFunctions <<utility>> {
        + bmw::mw::LogFatal(): LogStream
        + bmw::mw::LogError(): LogStream
        + bmw::mw::LogWarn(): LogStream
        + bmw::mw::LogInfo(): LogStream
        + bmw::mw::LogDebug(): LogStream
        + bmw::mw::LogVerbose(): LogStream
        + bmw::mw::LogFatal(std::string_view): LogStream
        + bmw::mw::LogError(std::string_view): LogStream
        + bmw::mw::LogWarn(std::string_view): LogStream
        + bmw::mw::LogInfo(std::string_view): LogStream
        + bmw::mw::LogDebug(std::string_view): LogStream
        + bmw::mw::LogVerbose(std::string_view): LogStream
        + bmw::mw::GetDefaultLogRecorder(): Recorder&
        + bmw::mw::test::SetLogRecorder(bmw::mw::log::Recorder *const): void
    }

    class bmw::mw::Logger {
        - context_: LoggingIdentifier
        + Logger(std::string_view ctxId)
        + LogFatal(): LogStream
        + LogError(): LogStream
        + LogWarn(): LogStream
        + LogInfo(): LogStream
        + LogDebug(): LogStream
        + LogVerbose(): LogStream
        + WithLevel(LogLevel): log::LogStream
        + IsLogEnabled(LogLevel): bool
        + IsEnabled(LogLevel): bool
        + GetContext(): std::string_view
    }

}


package "Not Mockable Part" {

    struct LoggingIdentifier {}

    class bmw::mw::log::detail::LogStreamFactory {
        + GetStream(LogLevel, ctxId: std::string_view = "DFLT"): LogStream
    }

    class bmw::mw::LogStream {
        - recorder_: Recorder&
        - slot_handle_: amp::optional<SlotHandle>
        - context_id_: detail::LoggingIdentifier
        - log_level_: LogLevel
        - LogStream(Recorder&, LogLevel, std::string_view)
        + LogStream(LogStream&&)
        + Flush(): void
    }

    class bmw::mw::log::SlotHandle {
        - recorder_to_slot_: std::array<SlotIndex, kMaxRecorders>
        - recorder_slot_available_: std::bitset<kMaxRecorders>
        - selected_recorder_: RecorderIdentifier
        + SlotHandle()
        + SlotHandle(SlotIndex)
        + GetSlotOfSelectedRecorder(): SlotIndex
        + GetSlot(RecorderIdentifier): SlotIndex
        + SetSlot(SlotIndex, RecorderIdentifier): void
        + GetSelectedRecorder(): RecorderIdentifier
        + SetSelectedRecorder(RecorderIdentifier): void
        + IsRecorderActive(RecorderIdentifier): bool
        + friend operator==(const SlotHandle& l_value, const SlotHandle& r_value): bool
        + friend operator!=(const SlotHandle& l_value, const SlotHandle& r_value): bool
        + kMaxRecorders: {static} constexpr std::size_t
    }

    class bmw::mw::log::detail::Runtime {
        - Runtime(Recorder *const recorder)
        - {static} Instance(Recorder *const): Runtime&
        - logger_container_instance_: LoggerContainer
        - recorder_instance_: Recorder
        - default_recorder_: std::unique_ptr<Recorder>
        + GetRecorder(): Recorder *
        + SetRecorder(Recorder *): void__
        + GetLoggerContainer(): bmw::mw::log::LoggerContainer&
    }

    struct SlotHandle::RecorderIdentifier {
        + value: std::size_t
    }

    enum bmw::mw::LogLevel {
        kOff = 0x00
        kFatal = 0x01
        kError = 0x02
        kWarn = 0x03
        kInfo = 0x04
        kDebug = 0x05
        kVerbose = 0x06
    }

}


package "Mockable Part" {

    class bmw::mw::log::detail::VerbosePayload {
        - buffer_: std::reference_wrapper<ByteVector>
        + VerbosePayload(std::size_t, std::string&)
        + Put(const Byte *, std::size_t): void
        + Put(const ReserveCallback, std::size_t): std::size_t
        + GetSpan(): amp::span<const std::uint8_t>
        + Reset(): void
        + WillOverflow(std::size_t): bool
        + RemainingCapacity(): std::size_t
        + SetBuffer(ByteVector&): void
    }

    struct LogEntry {
        + appId: dltid_t
        + ctxId: dltid_t
        + sessionId: dltid_t
        + logLevel: std::uint8_t
        + num_of_args: std::int8_t
        + payload: std::string
    }

    class bmw::mw::log::detail::LogRecord {
        - logEntry_: LogEntry
        - verbosePayload_: VerbosePayload
        + getLogEntry(): LogEntry&
        - getLogEntry() const: cosnt LogEntry&
        - getVerbosePayload(): detail::VerbosePayload&
        - getVerbosePayload() const: const detail::VerbosePayload&
    }

    entity TRACE_MACRO {}

    entity Configuration {}

    entity StatisticsReporter {}

    class bmw::mw::log::detail::DataRouterBackend {
        + ReserveSlot(): amp::optional<SlotHandle>
        + FlushSlot(const SlotHandle&)
        + GetLogRecord(const SlotHandle&): LogRecord
        - buffer_: CircularAllocator<bmw::mw::log::detail::LogRecord>
        - message_client_: std::unique_ptr<DatarouterMessageClient>
    }

    interface bmw::mw::log::detail::Backend {
        + ReserveSlot(): amp::optional<SlotHandle>
        + FlushSlot(const SlotHandle&)
        + GetLogRecord(const SlotHandle&): LogRecord
    }

    interface bmw::mw::log::Recorder {
        + Recorder()
        + StartRecord(context_id: std::string_view, LogLevel): amp::optional<SlotHandle>
        + StopRecord(const SlotHandle&): void
        + Log(SlotHandle, std::uint8_t): void
        + Log(SlotHandle, std::int8_t): void
    }

    class DataRouterRecorder {}

    class TextRecorder {}

    class FileRecorder {}

    class EmptyRecorder {}

    entity TextFormat {}

    class bmw::mw::log::LoggerContainer {
        - InsertNewLogger(std::string_view): Logger&
        - FindExistingLogger(std::string_view): amp::optional<std::reference_wrapper<Logger>>
        - stack_: WaitFreeStack<Logger>
        - default_logger_: Logger
        + GetLogger(std::string_view): Logger&
        + GetCapacity(): std::size_t
        + GetDefaultLogger(): Logger&
    }

    class "bmw::mw::log::detail::WaitFreeStack<Element>" as bmw::mw::log::detail::WaitFreeStack_of_Element {
        - elements_: std::vector<amp::optional<Element>>
        - elements_written_: std::vector<std::atomic_int>
        - write_index_: AtomicIndex
        - capacity_full_: AtomicBool
        + WaitFreeStack(std::size_t)
        + TryPush(Element&&): amp::optional<std::reference_wrapper<Element>>
        + Find(const FindPredicate<Element>&): amp::optional<std::reference_wrapper<Element>>
    }

}


bmw::mw::Logger --* LoggingIdentifier: owns
bmw::mw::Logger --|> bmw::mw::log::detail::LogStreamFactory: uses
bmw::mw::Logger --* bmw::mw::log::LoggerContainer: owns

FreeFunctions --|> bmw::mw::log::detail::LogStreamFactory: uses
FreeFunctions --|> bmw::mw::log::detail::Runtime

bmw::mw::log::detail::LogStreamFactory --|> bmw::mw::LogStream: create
bmw::mw::log::detail::LogStreamFactory --|> bmw::mw::log::detail::Runtime: get current record

bmw::mw::log::SlotHandle --* bmw::mw::LogStream: owns

bmw::mw::log::detail::VerbosePayload --* bmw::mw::log::detail::LogRecord: << creates and fills >>

LogEntry --* bmw::mw::log::detail::LogRecord: << creates and fills >>

bmw::mw::log::detail::LogRecord --* bmw::mw::log::detail::DataRouterBackend: << creates and fills >>

Configuration --* DataRouterRecorder: get application specific config

StatisticsReporter --* DataRouterRecorder

bmw::mw::log::detail::DataRouterBackend --* DataRouterRecorder: << reserve and flush slots >>
bmw::mw::log::detail::DataRouterBackend --|> TRACE_MACRO: << on sync >>
bmw::mw::log::detail::DataRouterBackend ..|> bmw::mw::log::detail::Backend

DataRouterRecorder --* bmw::mw::log::detail::Runtime: owns statically
DataRouterRecorder ..|> bmw::mw::log::Recorder
TextRecorder ..|> bmw::mw::log::Recorder
FileRecorder ..|> bmw::mw::log::Recorder
EmptyRecorder ..|> bmw::mw::log::Recorder

bmw::mw::log::Recorder --o bmw::mw::LogStream: records data
bmw::mw::log::Recorder ..> TextFormat: Log

bmw::mw::log::LoggerContainer --* bmw::mw::log::detail::Runtime: owns

bmw::mw::log::detail::WaitFreeStack_of_Element --* bmw::mw::log::LoggerContainer: owns


note "This diagram only illustrates the use-case of verbose logging." as N0
note "A user is allowed to use the Recorder interface for its abstraction, but it is not recommended due to its more complicated usage." as N1
note "For the time being, DataRouterRecorder will not only be a facade but also contain DLT specific logic. In this case, calling StartRecord() and StopRecord." as N2
note "In future this will be removed and we will stream into MwsrWriter." as N3

N1 .. bmw::mw::log::Recorder

N2 .. DataRouterRecorder

N3 .. bmw::mw::log::detail::VerbosePayload
N3 .. LogEntry
N3 .. TRACE_MACRO


@enduml