@startuml
start
if (Stack capacity is full?) then (yes)
:Current write index = write index;
if (Current write index >= number
of elements in stack) then (yes)
:Increment write index;
:Return null value;
:Push element to stack;
:Return element value;
stop
:Stack capacity full = true;
@enduml