@startuml datarouter_backend_class_diagram


class MsgClientBackend {
- shared_memory_writer_: SharedMemoryWriter&
- writer_file_name_: std::string
- message_passing_factory_: std::unique_ptr<MessagePassingFactory>
- use_dynamic_datarouter_ids_ : bool
---
+ MsgClientBackend(SharedMemoryWriter&amp;,
  const std::string&,
  std::unique_ptr<MessagePassingFactory>,
  const bool)
+ GetShMemWriter(): SharedMemoryWriter&
+ GetWriterFilename(): const std::string&
+ GetMsgPassingFactory(): std::unique_ptr<MessagePassingFactory>&
+ IsUsingDynamicDatarouterIDs(): bool
}


class MsgClientUtils {
- unistd_: std::unique_ptr<os::Unistd>
- pthread_: std::unique_ptr<os::Pthread>
- signal_: std::unique_ptr<os::Signal>
---
+ MsgClientUtils(std::unique_ptr<os::Unistd>,
  std::unique_ptr<os::Pthread>, std::unique_ptr<os::Signal>)
+ GetUnistd(): os::Unistd&
+ GetPthread(): os::Pthread&
+ GetSignal(): os::Signal&
}

class DataRouterBackend {
  - buffer_: CircularAllocator
  - message_client_: DatarouterMessageClient
  ---
  + DataRouterBackend(const std::size_t,
                      const LogRecord&,
                      DatarouterMessageClientFactory&,
                      const Configuration&,
                      WriterFactory)
  + ReserveSlot(): amp::optional<SlotHandle>
  + FlushSlot(const SlotHandle&): void
  + GetLogRecord(const SlotHandle&): LogRecord&
}

interface Backend {
}

interface DatarouterMessageClient {
  + Run(): void
  + Shutdown(): void
}

class DatarouterMessageClientImpl {
  - run_started_: bool
  - msg_client_ids_: MsgClientIdentifiers
  - use_dynamic_datarouter_ids_: bool
  - first_message_received_: std::atomic_bool
  - shared_memory_writer_: SharedMemoryWriter&
  - writer_file_name_: std::string
  - message_passing_factory_: std::unique_ptr<MessagePassingFactory>
  - stop_source_: amp::stop_source
  - thread_pool_: bmw::concurrency::ThreadPool
  --
  + DatarouterMessageClientImpl(const MsgClientIdentifiers&, MsgClientBackend, MsgClientUtils, const amp::stop_source)
  + Run(): void
  + Shutdown(): void
  + ConnectToDatarouter(): void
  + SendConnectMessage(): void
  - RunConnectTask(): bool
  - OnAcquireRequest(): void
  - UnlinkSharedMemoryFile(): void
  - HandleFirstMessageReceived(): void
  - RequestInternalShutdown(): void
  - CheckExitRequestAndSendConnectMessage(): void
  - BuildMessage(const DatarouterMessageIdentifier&,
                 const bmw::mw::com::message_passing::MediumMessagePayload&):
                 bmw::mw::com::message_passing::MediumMessage
  - SendMessage(const Message&): void
}

interface DatarouterMessageClientFactory {
  + CreateOnce(const std::string&, const std::string&): std::unique_ptr<DatarouterMessageClient>
}

class DatarouterMessageClientFactoryImpl {
  - created_once_: bool
  - config_: Configuration
  - message_passing_factory_: MessagePassingFactory
  - uinstd_: os::Uinstd
  - pthread_: os::Pthread
  ---
  + DatarouterMessageClientFactoryImpl(const Configuration&,
                                       std::unique_ptr<MessagePassingFactory>,
                                       std::unique_ptr<os::Unistd>,
                                       std::unique_ptr<os::Pthread>)
  + CreateOnce(const std::string&, const std::string&): std::unique_ptr<DatarouterMessageClient>
}

class SharedMemoryWriter {
  - shared_data_: SharedData&
  - alternating_writer_: WaitFreeAlternatingWriter
  - alternating_reader_: AlternatingReader
  - type_identifier_: atomic<TypeIdentifier>
  - moved_from: bool 
  ---
  + SharedMemoryWriter(SharedData&, UnmapCallback)
  + GetMaxPayloadSize(): Length
  + AllocAndWrite(const TimePoint, const TypeIdentifier, const Length, WriteCallback): void
  + AllocAndWrite(WriteCallback, const TypeIdentifier, const Length): void
  + TryRegisterType(info: Typeinfo): optional<TypeIdentifier>
  + ReadAcquired(): ReadAcquireResult
  + DetachWriter(): void
}

class "<<Shared Memory>>\nSharedData" as SharedData {
  + control_block: AlternatingControlBlock
  + linear_buffer_1_offset: Length
  + linear_buffer_2_offset: Length
  + number_of_drops_buffer_full: std::atomic<Length>
  + number_of_drops_invalid_size: std::atomic<Length>
  + writer_detached: std::atomic<bool>
  + producer_pid: pid_t
}

class WriterFactory {
  - osal_: OsalInstances
  - mmap_result_: amp::expected<void*, bmw::os::Error>
  - unmap_callback_: UnmapCallback
  - file_attributes_: LoggingClientFileNameResult
  ---
  + WriterFactory(OsalInstances)
  + Create(const std::size_t,
           const bool,
           const std::string_view): amp::optional<SharedMemoryWriter>
  + GetIdentifier(): std::string
  + GetFileName(): std::string
  - GetStaticLoggingClientFilename(const std::string_view): std::string
  - UnlinkExistingFile(const std::string&): void
  - OpenAndTruncateFile(const std::size_t,
                        const std::string&,
    flags: const bmw::os::Fcntl::Open):
    amp::optional<int32_t>
  - MapSharedMemory(const std::size_t,
                    const int32_t,
                    const std::string&):
    amp::optional<void* const>
  - IsMemoryAligned(void* const): bool
  - ConstructSharedData(void* const,
                        const std::size_t): SharedData*
  - PrepareFileNameAndUpdateOpenFlags(bmw::os::Fcntl::Open&,
    const bool,
    const std::string_view): LoggingClientFileNameResult
  - GetAlignedRingBufferAddress(const std::size_t,
      const std::string&,
      const bmw::os::Fcntl::Open):
    amp::optional<void* const>;
}

class WaitFreeAlternatingWriter {
  + Acquire(const Length length): amp::optional<AlternatingAcquiredData>
  + Release(const AlternatingAcquiredData&): void
}

class AlternatingReader {
  + Read(): amp::optional<amp::span<Byte>>
  + Switch(): void
}

class AlternatingControlBlock {
  + control_block_even: LinearControlBlock
  + control_block_odd: LinearControlBlock
  + switch_count_points_active_for_writing: std::atomic<std::uint32_t>
}

class LinearControlBlock {
  + data: amp::span<Byte>
  + acquired_index: std::atomic<Length>
  + written_index: std::atomic<Length>
  + number_of_writers: std::atomic<Length>
}

class MsgClientIdentifiers {
  - receiver_id_: std::string
  - this_process_id_: pid_t
  - app_id_: LoggingIdentifier
  - datarouter_uid_: uid_t
  - uid_: uid_t
  --
  + MsgClientIdentifiers(const std::string&,
      const pid_t,
      const LoggingIdentifier&,
      const uid_t,
      const uid_t)
  + GetReceiverID(): std::string&
  + GetThisProcID(): const pid_t&
  + GetAppID(): const LoggingIdentifier&
}

class "CircularAllocator<T>" as CircularAllocator {
}

interface MessagePassingFactory {
  + CreateReceiver(const std::string_view, concurrency::Executor&, const amp::span<const uid_t>,
                   const bmw::mw::com::message_passing::ReceiverConfig&, amp::pmr::memory_resource*): amp::pmr::unique_ptr<bmw::mw::com::message_passing::IReceiver>
  + CreateSender(const std::string_view, const amp::stop_token&,
                 const bmw::mw::com::message_passing::SenderConfig&, bmw::mw::com::message_passing::LoggingCallback, amp::pmr::memory_resource*): amp::pmr::unique_ptr<bmw::mw::com::message_passing::ISender>
}

class "<<Singleton>>\nbmw::platform::logger" as Logger {
  - writer: SharedMemoryWriter
}

class ConnectMessageFromClient {
  + appid: LoggingIdentifier
  + uid: uid_t
  + use_dynamic_identier: bool
  + random_part: std::array<std::string::value_type, 16>
  + operator==(const ConnectMessageFromClient&): bool
  + operator!=(const ConnectMessageFromClient&): bool
}

class LoggingFileNameResult {
  + file_name: std::string
  + identifier: std::string
}

class ThreadPool {
}

package "OSAL" {
  class OsalInstances {
    + fcntl_osal: std::unique_ptr<os::Fcntl>
    + unistd: std::unique_ptr<os::Unistd>
    + mman: std::unique_ptr<os::Mman>
    + stat_osal: std::unique_ptr<os::Stat>
  }

  class Unistd { }
  class Fcntl { }
  class Mman { }
  class Stat { }
  class Stdlib { }

  OsalInstances *-- Unistd
  OsalInstances *-- Fcntl
  OsalInstances *-- Mman
  OsalInstances *-- Stat
  OsalInstances *-- Stdlib
}

package mw::com::message_passing {
  class ISender {
  }
  
  class IReceiver {
  }

  class ShortMessage {
  }

  class MediumMessage {
  }
}

' Relationships
Backend <|.. DataRouterBackend
DatarouterMessageClient <|.. DatarouterMessageClientImpl
DatarouterMessageClientFactory <|.. DatarouterMessageClientFactoryImpl

CircularAllocator *-- DataRouterBackend
DataRouterBackend *-- DatarouterMessageClientImpl
DataRouterBackend <-- DatarouterMessageClient
DataRouterBackend <.. DatarouterMessageClientFactory
DatarouterMessageClientFactoryImpl ..> DatarouterMessageClientImpl : "creates"

SharedMemoryWriter o-- SharedData
SharedMemoryWriter *-- WaitFreeAlternatingWriter
SharedMemoryWriter *-- AlternatingReader
SharedMemoryWriter <.. DatarouterMessageClientImpl: uses
SharedMemoryWriter <.. MsgClientBackend : uses
DatarouterMessageClientImpl ..> MsgClientBackend
MsgClientBackend *-- MessagePassingFactory
DatarouterMessageUtils ..* DatarouterMessageClientImpl

MsgClientUtils --* DatarouterMessageClientImpl
Unistd --* MsgClientUtils
Pthread --* MsgClientUtils
Signal --* MsgClientUtils

SharedData *-- AlternatingControlBlock
AlternatingControlBlock *-- LinearControlBlock

WriterFactory ..> SharedMemoryWriter : "creates"
WriterFactory *-- OsalInstances
WriterFactory *-- LoggingFileNameResult
WriterFactory <.. DataRouterBackend: "uses"

DatarouterMessageClientImpl *-- MsgClientIdentifiers
DatarouterMessageClientImpl *-- SharedMemoryWriter
DatarouterMessageClientImpl *-- MessagePassingFactory

MessagePassingFactory *.. ISender
MessagePassingFactory *.. IReceiver
MessagePassingFactory *.. ShortMessage
MessagePassingFactory *.. MediumMessage
MessagePassingFactory *.. ThreadPool

Logger *-- SharedMemoryWriter

DatarouterMessageClientImpl --> ConnectMessageFromClient

note bottom of LinearControlBlock
  using Length = std::uint64_t;
end note

@enduml