@startuml wait_free_alternating_buffers

participant "Producer Thread\n(WaitFreeAlternatingWriter class)" as Producer
participant "Consumer Thread\n(AlternatingReader class)" as Consumer
participant "AlternatingControlBlock" as ControlBlock

note over ControlBlock
  **Initial State:**
  acquired_index_1 == 0, written_index_1 == 0, number_of_writers_1 == 0
  acquired_index_2 == 0, written_index_2 == 0, number_of_writers_2 == 0
  active_for_writing == 1
end note

Producer -> ControlBlock : Acquire(64 bytes)
note right
  number_of_writers_1.increment()
  acquired_index_1 == 72
  number_of_writers_1 == 1
end note

Producer -> Producer : WriteDataProducer1(acquired_data)
note right
  Writing on buffer 1, range [8:72)
end note

Consumer -> ControlBlock : Switch()
note right
  **Reset buffer 2 for writing:**
  acquired_index_2.store(0)
  written_index_2.store(0)
  
  **Toggle future writers to use buffer 2:**
  active_for_writing.store(2)
  
  **Block until pending writers finished on buffer 1.**
end note

Producer -> ControlBlock : Release(64 bytes)
note right
  written_index_1 == (8 + 64)
  number_of_writers_1 == 0
end note

note over ControlBlock
  **Final State:**
  acquired_index_1 == 72, written_index_1 == 72, number_of_writers_1 == 0
  acquired_index_2 == 24, written_index_2 == 24, number_of_writers_2 == 0
  active_for_writing == 2
end note

note left of Producer
  **Linear Buffer 1 Content:**
  
  **[0:8)** - Length of Packet 1
  Data: 64
  
  **[8:72)** - Producer 1, Packet 1
  Data: WriteDataProducer1()
end note

note right of Consumer
  **Linear Buffer 2 Content:**
  
  **[0:8)** - Length of Packet 2
  Data: 16
  
  **[8:24)** - Producer1, Packet 2
  Data: Packet 2
end note

@enduml